# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0ee2a8836fc7211c86969405fd1bb694"
name = "custom-app"
handle = "custom-app-649"
application_url = "https://carry-expanding-fin-channel.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dawn-customized-sandbox.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,write_products"

[auth]
redirect_urls = [
  "https://carry-expanding-fin-channel.trycloudflare.com/auth/callback",
  "https://carry-expanding-fin-channel.trycloudflare.com/auth/shopify/callback",
  "https://carry-expanding-fin-channel.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
